({
	"nl" : {
		"question1"	: '{On a sunny morning|On a beautiful afternoon}, <var>person(1)</var> rode <var>his(1)</var> bicycle to a farm that sold bags of <var>plural(fruit(1))</var> for $<var>fruit_1</var> each and bags of <var>plural(fruit(2))</var> for $<var>fruit_2</var> each.',
		"question2"	: '<var>person(1)</var> decided to buy a bag of <var>plural(fruit(1))</var> and a bag of <var>plural(fruit(2))</var> {before heading home|because those were <var>his(1)</var> favorite kinds of fruit|}.',
		"question3"	: 'How much did <var>person(1)</var> need to pay for <var>his(1)</var> produce?',
		"question4"	: '{On Monday|Last week}, <var>person(1)</var> and <var>person(2)</var> decided to see how fast they could sprint <var>meters</var> meters. They asked their friend <var>person(3)</var> to time them with a stopwatch.',
		"question5"	: "{After <var>time_3</var> minutes, <var>person(3)</var> agreed to time the runners</var>.|} <var>person(1)</var> sprinted first and ran <var>meters</var> meters in <var>time_1</var> seconds. When it was <var>person(2)</var>'s turn, <var>he(2)</var> sped off and completed the run in <var>time_2</var> seconds.",
		"question6"	: 'How much faster was <var>person(2)</var> than <var>person(1)</var>?',
		"question7"	: "{Last Monday|On Saturday}, <var>person(1)</var>'s parents gave birth to twins and named them <var>person(2)</var> and <var>person(3)</var>. When they were first born, <var>person(2)</var> weighed <var>weight_1</var> pounds{ and was <var>height_1</var> inches tall|}, and <var>person(3)</var> weighed <var>weight_2</var> pounds {and was <var>height_2</var> inches tall|}.",
		"question8"	: 'How much did the babies weigh in total?',
		"question9"	: '{On Tuesday,|Last Thursday,|} <var>person(1)</var> walked to <var>an(store(1))</var> store {<var>timeofday(1)</var>|} and{, after browsing for <var>time_1</var> minutes,|} decided to buy a <var>storeItem(1,1)</var> for $<var>price_1</var>. <var>person(1)</var> handed the salesperson $<var>amount_paid</var> for <var>his(1)</var> purchase.',
		"question10": 'How much change did <var>person(1)</var> receive?',
		"question11": "During a recent rainstorm, <var>rain_1</var> inches of rain fell in <var>person(1)</var>'s hometown, and <var>rain_2</var> inches of rain fell in <var>person(2)</var>'s hometown. {During the same storm, <var>snow_1</var> inches of snow fell in <var>person(3)</var>'s hometown.|}",
		"question12": "How much more rain fell in <var>person(2)</var>'s town than in <var>person(1)</var>'s town?",
		"question13": '{To get to school each morning|To get to work each morning|To visit <var>his(1)</var> grandmother}, <var>person(1)</var> takes <var>an(vehicle(1))</var> <var>distance_1</var> <var>plural(distance(1))</var> and <var>an(vehicle(2))</var> <var>distance_2</var> <var>plural(distance(1))</var>. {In total, the journey takes <var>time_1</var> minutes.|}',
		"question14": "How many <var>plural(distance(1))</var> is <var>person(1)</var>'s journey in total?",
		"question15": "<var>person(1)</var> needs to pay $<var>solution</var>.",
		"question16": "<var>person(2)</var> was <var>solution</var> seconds faster than <var>person(1)</var>.",
		"question17": "Together, the babies weigh <var>solution</var> pounds.",
		"question18": "<var>person(1)</var> received $<var>solution</var> in change.",
		"question19": "<var>person(2)</var>'s town received <var>solution</var> inches more rain than <var>person(1)</var>'s town.",
		"question20": "<var>person(1)</var> travels <var>solution</var> <var>plural(distance(1))</var> in total.",
		
		"hint1"		: 'To find the total amount <var>person(1)</var> needs to pay, we need to add the price of the <var>plural(fruit(1))</var> and the price of the <var>plural(fruit(2))</var>.',
		"hint2"		: 'Price of <var>plural(fruit(1))</var> + price of <var>plural(fruit(2))</var> = total price.',
		"hint3"		: 'To find how much faster <var>person(2)</var> was than <var>person(1)</var>, we need to find the difference between their times.',
		"hint4"		: "<var>person(1)</var>'s time - <var>person(2)</var>'s time = difference in times.",
		"hint5"		: 'To find the weights of the 2 babies, we need to add their weights together.',
		"hint6"		: "<var>person(2)</var>'s weight + <var>person(3)</var>'s weight = total weight.",
		"hint7"		: 'To find out how much change <var>person(1)</var> received, we can subtract the price of the <var>storeItem(1,1)</var> from the amount of money <var>he(1)</var> paid.',
		"hint8"		: 'The amount <var>person(1)</var> paid - the price of the <var>storeItem(1,1)</var> = the amount of change <var>person(1)</var> received.',
		"hint9"		: "To find the difference in rainfall, we can subtract the amount of rain in <var>person(1)</var>'s town from the amount of rain in <var>person(2)</var>'s town.",
		"hint10"	: "Rain in <var>person(2)</var>'s town - rain in <var>person(1)</var>'s town = the difference in rain between the two towns.",
		"hint11"	: 'To find the total distance <var>person(1)</var> travels, we need to add the two distances together.',
		"hint12"	: 'Distance on <var>vehicle(1)</var> + distance on <var>vehicle(2)</var> = total distance.'
		}
})