({
	"nl" : {
		"question1"	: '{Op een mooie ochtend|Op een prachtige middag} reed <var>person(1)</var> op <var>his(1)</var> fiets naar een boerderij waar fruit werd verkocht. Een zak met <var>plural(fruit(1))</var> kostte &euro;<var>fruit_1</var> en een zak met <var>plural(fruit(2))</var> kostte &euro;<var>fruit_2</var>.',
		"question2"	: '<var>person(1)</var> besloot een zak <var>plural(fruit(1))</var> en een zak <var>plural(fruit(2))</var> te kopen{ voordat <var>he(1)</var> naar huis ging|, omdat dat <var>his(1)</var> favoriete soorten fruit zijn|}.',
		"question3"	: 'Hoeveel moest <var>person(1)</var> betalen voor <var>his(1)</var> aankoop?',
		"question4"	: '{Op maandag|Afgelopen week} besloten <var>person(1)</var> en <var>person(2)</var> om te kijken wie er sneller kon sprinten over <var>meters</var> meter. Ze vroegen <var>person(3)</var> om hun tijd op te nemen met een stopwatch.',
		"question5"	: "{Na <var>time_3</var> minuten besloot <var>person(3)</var> om de tijd op te nemen.|} <var>person(1)</var> sprintte eerst en rende <var>meters</var> meter in <var>time_1</var> seconden. Toen het de beurt was aan <var>person(2)</var>, spoot <var>he(2)</var> weg en voltooide de race in <var>time_2</var> seconden.",
		"question6"	: 'Hoeveel was <var>person(2)</var> sneller dan <var>person(1)</var>?',
		"question7"	: "{Afgelopen maandag|Op zaterdag} kregen de ouders van <var>person(1)</var> een tweeling, die ze <var>person(2)</var> en <var>person(3)</var> noemden. Bij de geboorte woog <var>person(2)</var> <var>weight_1</var> pond{ en was <var>height_1</var> centimeter lang|}. <var>person(3)</var> woog <var>weight_2</var> pond {en was <var>height_2</var> centimeter lang|}.",
		"question8"	: 'Hoeveel wogen de babies samen?',
		"question9"	: '{Op dinsdag|Afgelopen donderdag|} liep <var>person(1)</var> naar een <var>(store(1))</var> en besloot om een <var>storeItem(1,1)</var> te kopen voor &euro;<var>price_1</var>. <var>person(1)</var> gaf bij de kassa &euro;<var>amount_paid</var> voor <var>his(1)</var> aankoop.',
		"question10": 'Hoeveel wisselgeld kreeg <var>person(1)</var>?',
		"question11": "Tijdens een herfststorm viel er <var>rain_1</var> centimter regen in het dorp waar <var>person(1)</var> woont en <var>rain_2</var> centimeter in het dorp waar <var>person(2)</var> woont. {Tijdens diezelfde storm viel er <var>snow_1</var> centimeter sneeuw in de plaats waar <var>person(3)</var> vandaan komt.|}",
		"question12": "Hoeveel centimeter regen viel er meer in het dorp waar <var>person(2)</var> woont dan in het dorp waar <var>person(1)</var> woont?",
		"question13": '{Om \'s morgens op school te komen|Om \'s morgens op <var>his(1)</var> werk te komen|Om <var>his(1)</var> oma te bezoeken}, reist <var>person(1)</var> <var>distance_1</var> kilometer met de <var>vehicle(1)</var>  en  <var>distance_2</var> kilometer met de <var>(vehicle(2))</var>. {De reis duurt bij elkaar <var>time_1</var> minuten.|}',
		"question14": "Hoeveel kilometer legt <var>person(1)</var> bij elkaar af?",
		"question15": "<var>person(1)</var> moet &euro;<var>solution</var> betalen.",
		"question16": "<var>person(2)</var> was <var>solution</var> seconden sneller dan <var>person(1)</var>.",
		"question17": "Samen wegen de babies <var>solution</var> pond.",
		"question18": "<var>person(1)</var> ontving &euro;<var>solution</var> wisselgeld.",
		"question19": "In het dorp van <var>person(2)</var> viel <var>solution</var> centimter meer regen dan in het dorp van <var>person(1)</var>.",
		"question20": "<var>person(1)</var> legt bij elkaar <var>solution</var> kilometer af.",
		
		"hint1"		: 'Om het totale bedrag te vinden dat <var>person(1)</var> moet betalen, tellen we de prijs van de <var>plural(fruit(1))</var> op bij de prijs van de <var>plural(fruit(2))</var>.',
		"hint2"		: 'Prijs van de <var>plural(fruit(1))</var> + prijs van de <var>plural(fruit(2))</var> = totale prijs.',
		"hint3"		: 'Om te achterhalen hoeveel <var>person(2)</var> sneller was dan <var>person(1)</var>, moeten we het verschil tussen hun beide tijden uitrekenen.',
		"hint4"		: "Tijd van <var>person(1)</var> - tijd van <var>person(2)</var>  = verschil in tijd.",
		"hint5"		: 'Om het gewicht van de 2 babies te bepalen, tellen we de beide gewichten bij elkaar op.',
		"hint6"		: "Gewicht van <var>person(2)</var> + gewicht van <var>person(3)</var> = totale gewicht.",
		"hint7"		: 'Om te weten hoeveel wisselgeld <var>person(1)</var> kreeg, trekken we de prijs van de <var>storeItem(1,1)</var> af van het bedrag dat <var>he(1)</var> betaalde.',
		"hint8"		: 'Het bedrag dat <var>person(1)</var> betaalde - de prijs van de <var>storeItem(1,1)</var> = het wisselgeld dat <var>person(1)</var> ontving.',
		"hint9"		: "Om het verschil in neerslag te berekenen, trekken we de hoeveelheid regen in het dorp van <var>person(1)</var>af van de hoeveelheid regen in het dorp van <var>person(2)</var>.",
		"hint10"	: "Rain in <var>person(2)</var>'s town - rain in <var>person(1)</var>'s town = the difference in rain between the two towns.",
		"hint11"	: 'Om de afstand te vinden die <var>person(1)</var> aflegde, tellen we de beide afstanden bij elkaar op.',
		"hint12"	: 'Afstand met de <var>vehicle(1)</var> + afstand met de <var>vehicle(2)</var> = totale afstand.'
		}
})