({
	"nl" : {
		"question1"	: '{Op een mooie ochtend|Op een prachtige middag}, reed <var>person(1)</var> op <var>his(1)</var> fiets naar een boerderij waar fruit werd verkocht. Een zak met <var>plural(fruit(1))</var> kostte &euro;<var>fruit_1</var> en een zak met <var>plural(fruit(2))</var> kostte &euro;<var>fruit_2</var> each.',
		"question2"	: '<var>person(1)</var> decided to buy a bag of <var>plural(fruit(1))</var> and a bag of <var>plural(fruit(2))</var> {before heading home|because those were <var>his(1)</var> favorite kinds of fruit|}.',
		"question3"	: 'How much did <var>person(1)</var> need to pay for <var>his(1)</var> produce?',
		"question4"	: '{On Monday|Last week}, <var>person(1)</var> and <var>person(2)</var> decided to see how fast they could sprint <var>meters</var> meters. They asked their friend <var>person(3)</var> to time them with a stopwatch.',
		"question5"	: "{After <var>time_3</var> minutes, <var>person(3)</var> agreed to time the runners</var>.|} <var>person(1)</var> sprinted first and ran <var>meters</var> meters in <var>time_1</var> seconds. When it was <var>person(2)</var>'s turn, <var>he(2)</var> sped off and completed the run in <var>time_2</var> seconds.",
		"question6"	: 'How much faster was <var>person(2)</var> than <var>person(1)</var>?',
		"question7"	: "{Last Monday|On Saturday}, <var>person(1)</var>'s parents gave birth to twins and named them <var>person(2)</var> and <var>person(3)</var>. When they were first born, <var>person(2)</var> weighed <var>weight_1</var> pounds{ and was <var>height_1</var> inches tall|}, and <var>person(3)</var> weighed <var>weight_2</var> pounds {and was <var>height_2</var> inches tall|}.",
		"question8"	: 'How much did the babies weigh in total?',
		"question9"	: '{On Tuesday,|Last Thursday,|} <var>person(1)</var> walked to <var>an(store(1))</var> store {<var>timeofday(1)</var>|} and{, after browsing for <var>time_1</var> minutes,|} decided to buy a <var>storeItem(1,1)</var> for &euro;<var>price_1</var>. <var>person(1)</var> handed the salesperson &euro;<var>amount_paid</var> for <var>his(1)</var> purchase.',
		"question10": 'How much change did <var>person(1)</var> receive?',
		"question11": "During a recent rainstorm, <var>rain_1</var> inches of rain fell in <var>person(1)</var>'s hometown, and <var>rain_2</var> inches of rain fell in <var>person(2)</var>'s hometown. {During the same storm, <var>snow_1</var> inches of snow fell in <var>person(3)</var>'s hometown.|}",
		"question12": "How much more rain fell in <var>person(2)</var>'s town than in <var>person(1)</var>'s town?",
		"question13": '{Om \'s morgens op school te komen|Om \'s morgens op <var>his(1)</var> werk te komen|Om <var>his(1)</var> oma te bezoeken}, reist <var>person(1)</var> <var>distance_1</var> <var>plural(distance(1))</var> met de <var>an(vehicle(1))</var>  en  <var>distance_2</var> <var>plural(distance(1))</var> met de <var>an(vehicle(2))</var>. {De reis duurt bij elkaar <var>time_1</var> minuten.|}',
		"question14": "Hoeveel <var>plural(distance(1))</var> is de reis van <var>person(1)</var> bij elkaar?",
		"question15": "<var>person(1)</var> moet &euro;<var>solution</var> betalen.",
		"question16": "<var>person(2)</var> was <var>solution</var> seconden sneller dan <var>person(1)</var>.",
		"question17": "Samen wegen de babies <var>solution</var> pond.",
		"question18": "<var>person(1)</var> ontving &euro;<var>solution</var> wisselgeld.",
		"question19": "In het dorp van <var>person(2)</var> viel <var>solution</var> centimter meer regen dan in het dorp van <var>person(1)</var>.",
		"question20": "<var>person(1)</var> legt bij elkaar <var>solution</var> <var>plural(distance(1))</var> af.",
		
		"hint1"		: 'Om het totale bedrag te vinden dat <var>person(1)</var> moet betalen, tellen we de prijs van de <var>plural(fruit(1))</var> op bij de prijs van de <var>plural(fruit(2))</var>.',
		"hint2"		: 'Prijs van de <var>plural(fruit(1))</var> + prijs van de <var>plural(fruit(2))</var> = totale prijs.',
		"hint3"		: 'Om te achterhalen hoeveel <var>person(2)</var> sneller was dan <var>person(1)</var>, moeten we het verschil tussen hun beide tijden uitrekenen.',
		"hint4"		: "Tijd van <var>person(1)</var> - tijd van <var>person(2)</var>  = verschil in tijd.",
		"hint5"		: 'Om het gewicht van de 2 babies te bepalen, tellen we de beide gewichten bij elkaar op.',
		"hint6"		: "Gewicht van <var>person(2)</var> + gewicht van <var>person(3)</var> = totale gewicht.",
		"hint7"		: 'To find out how much change <var>person(1)</var> received, we can subtract the price of the <var>storeItem(1,1)</var> from the amount of money <var>he(1)</var> paid.',
		"hint8"		: 'The amount <var>person(1)</var> paid - the price of the <var>storeItem(1,1)</var> = the amount of change <var>person(1)</var> received.',
		"hint9"		: "To find the difference in rainfall, we can subtract the amount of rain in <var>person(1)</var>'s town from the amount of rain in <var>person(2)</var>'s town.",
		"hint10"	: "Rain in <var>person(2)</var>'s town - rain in <var>person(1)</var>'s town = the difference in rain between the two towns.",
		"hint11"	: 'To find the total distance <var>person(1)</var> travels, we need to add the two distances together.',
		"hint12"	: 'Distance on <var>vehicle(1)</var> + distance on <var>vehicle(2)</var> = total distance.'
		}
})