({
	"nl" : {
		"question1"	: 'If there were initially <var>TOTAL</var> slices, what fraction of the <var>pizza( 1 )</var> was eaten?',
		"question2"	: 'If there were <var>plural(LEFT, "slice")</var> remaining, what fraction of the <var>pizza( 1 )</var> was eaten?',
		"question3"	: 'If <var>person( 1 )</var> ate <code>\dfrac{<var>A</var>}{<var>TOTAL</var>}</code> of the <var>pizza( 1 )</var>, what fraction of the <var>pizza( 1 )</var> was eaten?',
		"question4"	: 'If there were initially <var>TOTAL</var> slices, what fraction of the <var>pizza( 1 )</var> is remaining?',
		"question5"	: 'If <var>person( 1 )</var> ate <code>\dfrac{<var>A</var>}{<var>TOTAL</var>}</code> of the <var>pizza( 1 )</var>, what fraction of the <var>pizza( 1 )</var> is remaining?',
		"question6"	: 'How many people went to <var>person( 1 )</var>’s birthday party?',
		"question7"	: 'How much money did <var>person( 1 )</var> spend?',
		"question8"	: 'How much money did <var>person( 1 )</var> spend on canned food?',
		"question9"	: 'How many gallons of gas were left in the tank?',
		"question10": 'How many adults were at the picnic?',
		
		"info1"     : 'Round to the nearest cent, or hundredth of a dollar.',
		"info2"     : 'Round to the nearest cent, or hundredth of a dollar.',
		
		"problem1"  : '<var>person( 1 )</var> ate <var>plural( A, "slice" )</var> of <var>pizza( 1 )</var>, and <var>person( 2 )</var> ate <var>plural( B, "slice" )</var>.',
		"problem2"  : '<var>person( 1 )</var> ate <var>plural( A, "slice" )</var> of <var>pizza( 1 )</var>, and <var>person( 2 )</var> ate <var>plural( B, "slice" )</var>.',
		"problem3"  : '<var>person( 1 )</var> ate <var>plural( A, "slice" )</var> of <var>pizza( 1 )</var>, and <var>person( 2 )</var> ate <var>plural( B, "slice" )</var>.',
		"problem4"  : '<var>person( 1 )</var> ate <var>plural( A, "slice" )</var> of <var>pizza( 1 )</var>, and <var>person( 2 )</var> ate <var>plural( B, "slice" )</var>.',
		"problem5"  : '<var>person( 1 )</var> ate <var>plural( A, "slice" )</var> of <var>pizza( 1 )</var>, and <var>person( 2 )</var> ate <var>plural( B, "slice" )</var>.',
		"problem6"  : '<var>person( 1 )</var> invited <var>INVITEES</var> friends to <var>his( 1 )</var> birthday party. Some people had other plans and could not attend, but <var>N</var>/<var>D</var> of the people <var>person( 1 )</var> invited were able to attend.',
		"problem7"  : 'After saving up for a while, <var>person( 1 )</var> had $<var>AMOUNT</var> in <var>his( 1 )</var> piggy bank, and <var>he( 1 )</var> spent <var>N</var>/<var>D</var> of that money on books at the bookstore.',
		"problem8"  : 'Every day <var>person( 1 )</var> put the extra change from <var>his( 1 )</var> pockets into a glass jar. After <var>randRange( 10, 30 )</var> weeks, <var>person( 1 )</var> had saved up $<var>AMOUNT</var>. <var>person( 1 )</var> decided to use <var>N</var>/<var>D</var> of the money from the jar to buy canned food for a homeless shelter.',
		"problem9"  : 'Before leaving on a road trip, <var>person( 1 )</var> filled up <var>his( 1 )</var> gas tank, which holds <var>GALLONS</var> gallons of gas. After <var>0.5 * randRange( 3 / 0.5, 10 / 0.5 )</var> hours, <var>person( 1 )</var> noticed that the gas tank was <var>N</var>/<var>D</var> full.',
		"problem10" : '<var>ATTENDEES</var> people had a picnic in the park. <var>N</var>/<var>D</var> of the people at the picnic were adults.',
		
		
		"hint0"     : '<code>\text{fraction of <var>pizza( 1 )</var> eaten} = \dfrac{\text{number of slices eaten}}{\text{number slices total}}</code>',
		"hint1"		: 'They ate <code>\color{#6495ED}{<var>A + B</var>}</code> out of <code><var>TOTAL</var></code> slices.',
		"hint2"		: 'They ate <code>\dfrac{<var>A + B</var>}{<var>TOTAL</var>}</code> of the <var>pizza( 1 )</var>.',
		"hint3"		: 'Since they ate <var>A + B</var> slices of <var>pizza( 1 )</var> with <var>plural( LEFT, "slice" )</var> remaining, they must have begun with <var>TOTAL</var> slices.',
		"hint4"		: 'They ate <code>\color{#6495ED}{<var>A + B</var>}</code> out of <code><var>TOTAL</var></code> slices.',
		"hint5"		: 'They ate <code>\dfrac{<var>A + B</var>}{<var>TOTAL</var>}</code> of the <var>pizza( 1 )</var>.',
		"hint6"		: 'If <var>plural( A, "slice")</var> represent<var>A &gt; 1 ? "" : "s"</var> <code>\dfrac{<var>A</var>}{<var>TOTAL</var>}</code> of the <var>pizza( 1 )</var>, there must have been a total of <var>TOTAL</var> slices.',
		"hint7"		: 'They ate <code>\color{#6495ED}{<var>A + B</var>}</code> out of <code><var>TOTAL</var></code> slices.',
		"hint8"		: 'They ate <code>\dfrac{<var>A + B</var>}{<var>TOTAL</var>}</code> of the <var>pizza( 1 )</var>.',
		"hint9"		: 'Together they ate <var>A + B</var> slices, which leaves <var>LEFT</var> out of <var>TOTAL</var> slices remaining.',
		"hint10"	: 'There is <code>\dfrac{<var>LEFT</var>}{<var>TOTAL</var>}</code> of the <var>pizza( 1 )</var> remaining.',
		"hint11"	: 'If <var>plural( A, "slice" )</var> represent<var>A &gt; 1 ? "" : "s"</var> <code>\dfrac{<var>A</var>}{<var>TOTAL</var>}</code> of the <var>pizza( 1 )</var>, there must have been a total of <var>TOTAL</var> slices.',
		"hint12"	: 'Together they ate <var>A + B</var> slices, which leaves <var>LEFT</var> out of <var>TOTAL</var> slices remaining.',
		"hint13"	: 'There is <code>\dfrac{<var>LEFT</var>}{<var>TOTAL</var>}</code> of the <var>pizza( 1 )</var> remaining.',
		"hint14"	: 'We can multiply <code>\dfrac{<var>N</var>}{<var>D</var>}</code> by <code><var>INVITEES</var></code> to find out how many people attended the party.',
		"hint15"	: '<code>\color{#e00}{\dfrac{<var>N * INVITEES</var>}{<var>D</var>}} = <var>SOLUTION</var></code>',
		"hint16"	: 'We, we can multiply <code><var>AMOUNT</var></code> by <code>\dfrac{<var>N</var>}{<var>D</var>}</code>  to find out how much money <var>person( 1 )</var> spent.',
		"hint17"	: '<strong><var>person( 1 )</var> spent $<var>SOLUTION</var> on books.</strong>',
		"hint18"	: 'We can multiply <code><var>AMOUNT</var></code> by <code>\dfrac{<var>N</var>}{<var>D</var>}</code> to find out how much money <var>person( 1 )</var> spent on canned food.',
		"hint19"	: '<strong><var>person( 1 )</var> spent $<var>SOLUTION</var> on canned food for the homeless shelter.</strong>',
		"hint20"	: 'Since a fraction of the gas in <var>his( 1 )</var> tank was left, we can multiply <code><var>GALLONS</var></code> by <code>\dfrac{<var>N</var>}{<var>D</var>}</code> to find out how much gas was left in the tank.',
		"hint21"	: '<strong><var>person( 1 )</var> had <var>SOLUTION</var> gallons of gas left in <var>his( 1 )</var> tank when <var>he( 1 )</var> checked.</strong>',
		"hint22"	: 'We can multiply <code><var>ATTENDEES</var></code> by <code>\dfrac{<var>N</var>}{<var>D</var>}</code> to find out how many people at the picnic were adults.',
		"hint23"	: '<strong><var>SOLUTION</var> people at the picnic were adults.</strong>'
		}
})