({
	"nl" : {
		"question1"	: 'Als er oorspronkelijk <var>TOTAL</var> stukken waren, welk gedeelte van de <var>pizza( 1 )</var> is dan opgegeten?',
		"question2"	: 'Als er <var>plural(LEFT, "stuk", "stukken")</var> over zijn, welk gedeelte van de <var>pizza( 1 )</var> is dan opgegeten?',
		"question3"	: 'Als <var>person( 1 )</var> <code>\\dfrac{<var>A</var>}{<var>TOTAL</var>}</code> van de <var>pizza( 1 )</var> opat, welk gedeelte van de <var>pizza( 1 )</var> was dan opgegeten?',
		"question4"	: 'Als er oorspronkelijk <var>TOTAL</var> stukken waren, welk gedeelte van de <var>pizza( 1 )</var> is dan nog over?',
		"question5"	: 'Als <var>person( 1 )</var> <code>\\dfrac{<var>A</var>}{<var>TOTAL</var>}</code> van de <var>pizza( 1 )</var> opat, welk gedeelte van de <var>pizza( 1 )</var> was dan nog over?',
		"question6"	: 'Hoeveel mensen zijn naar de verjaardag van <var>person( 1 )</var> gegaan?',
		"question7"	: 'Hoeveel geld heeft <var>person( 1 )</var> uitgegeven?',
		"question8"	: 'Hoeveel geld gaf <var>person( 1 )</var> uit aan voedsel?',
		"question9"	: 'Hoeveel liter benzine zit er nog in de tank?',
		"question10": 'Hoeveel volwassenen waren er op de picknick?',
		"info1"     : 'Rond af tot op de cent, of 1 honderdste van een euro.',
		"info2"     : 'Rond af tot op de cent, of 1 honderdste van een euro.',
		"problem1"  : '<var>person( 1 )</var> at <var>plural( A, "stuk", "stukken" )</var> <var>pizza( 1 )</var> en <var>person( 2 )</var> at <var>plural( B, "stuk","stukken")</var> <var>pizza( 1 )</var>.',
		"problem6"  : '<var>person( 1 )</var> nodigde <var>INVITEES</var> vrienden uit voor <var>his( 1 )</var> verjaardag. Sommige mensen hadden andere plannen en konden niet komen, maar <var>N</var>/<var>D</var> van de mensen die <var>person( 1 )</var> had uitgenodigd konden komen.',
		"problem7"  : 'Na een tijdje sparen had <var>person( 1 )</var> &euro;<var>AMOUNT</var> in <var>his( 1 )</var> spaarpot. <var>He( 1 )</var> gaf <var>N</var>/<var>D</var> van dat geld uit om boeken te kopen.',
		"problem8"  : 'Elke dag stopt <var>person( 1 )</var> het kleingeld uit <var>his( 1 )</var> zak in een glazen pot. Na <var>randRange( 10, 30 )</var> weken heeft <var>person( 1 )</var> &euro;<var>AMOUNT</var> gespaard. <var>person( 1 )</var> besluit om <var>N</var>/<var>D</var> van dat geld te gebruiken om voedsel te kopen voor een opvangcentrum voor daklozen.',
		"problem9"  : 'Voordat <var>person( 1 )</var> op vakantie gaat, gooit <var>he( 1 )</var> <var>his( 1 )</var> tank, waar totaal <var>GALLONS</var> liter in kan, vol met benzine. Na <var>0.5 * randRange( 3 / 0.5, 10 / 0.5 )</var> uur rijden, ziet <var>person( 1 )</var> dat <var>his( 1 )</var> benzinetank nog <var>N</var>/<var>D</var> vol is.',
		"problem10" : 'Op een picknick in het park waren in totaal <var>ATTENDEES</var> mensen. Van die mensen was <var>N</var>/<var>D</var> volwassen.',
		
		"hint1"		: 'Ze aten <code>\\color{#6495ED}{<var>A + B</var>}</code> van de  <code><var>TOTAL</var></code> stukken.',
		"hint2"		: 'Ze aten <code>\\dfrac{<var>A + B</var>}{<var>TOTAL</var>}</code> van de <var>pizza( 1 )</var>.',
		"hint3"		: 'Omdat ze <var>A + B</var> stukken <var>pizza( 1 )</var> aten en er <var>plural( LEFT, "stuk","stukken" )</var> overbleven, moeten er aan het begin <var>TOTAL</var> stukken zijn geweest.',
		"hint6"		: 'Als <var>plural( A, "stuk","stukken")</var> gelijk is aan <code>\\dfrac{<var>A</var>}{<var>TOTAL</var>}</code> van de <var>pizza( 1 )</var>, dan moeten er totaal <var>TOTAL</var> stukken zijn geweest.',
		"hint7"     : '<code>\\text{gedeelte van <var>pizza( 1 )</var> opgegeten} = \\dfrac{\\text{aantal opgegeten stukken}}{\\text{totaal aantal stukken}}</code>',
		"hint9"		: 'Samen aten ze <var>A + B</var> stukken, zodat er <var>LEFT</var> van de <var>TOTAL</var> stukken overbleven.',
		"hint10"	: '<code>\\dfrac{<var>LEFT</var>}{<var>TOTAL</var>}</code> van de <var>pizza( 1 )</var> blijft over.',
		
		"hint11"	: '<code>\\text{gedeelte van de <var>pizza( 1 )</var> dat overblijft} = \\dfrac{\text{aantal stukken dat overblijft}}{\\text{totaal aantal stukken}}</code>',
		"hint12"	: 'Samen aten ze  <var>A + B</var> stukken, waardoor er <var>LEFT</var> van de <var>TOTAL</var> stukken overblijft.',
		"hint13"	: '<code>\\dfrac{<var>LEFT</var>}{<var>TOTAL</var>}</code> van de  <var>pizza( 1 )</var> blijft over.',
		"hint14"	: 'We kunnen <code>\\dfrac{<var>N</var>}{<var>D</var>}</code> vermenigvuldigen met <code><var>INVITEES</var></code> om te weten hoeveel mensen er op het feest kwamen.',
		"hint15"	: '<var>SOLUTION</var> mensen bezochten het feest van <var>person( 1 )</var>.',
		"hint16"	: 'We kunnen <code><var>AMOUNT</var></code> vermenigvuldigen met <code>\\dfrac{<var>N</var>}{<var>D</var>}</code>  om te weten te komen hoeveel <var>person( 1 )</var> heeft uitgegeven.',
		"hint17"	: '<strong><var>person( 1 )</var> gaf &euro;<var>SOLUTION</var> uit aan boeken.</strong>',
		"hint18"	: 'We kunnen <code><var>AMOUNT</var></code> vermenigvuldigen met <code>\\dfrac{<var>N</var>}{<var>D</var>}</code> om te weten te komen hoeveel geld <var>person( 1 )</var> uitgaf aan voedsel.',
		"hint19"	: '<strong><var>person( 1 )</var> gaf &euro;<var>SOLUTION</var> uit aan voedsel voor het opvangcentrum voor daklozen.</strong>',
		"hint20"	: 'Omdat een gedeelte van de benzine in <var>his( 1 )</var> tank over was, kunnen we <code><var>GALLONS</var></code> vermenigvuldigen met <code>\\dfrac{<var>N</var>}{<var>D</var>}</code> om te achterhalen hoeveel benzine er nog in de tank zit.',
		"hint21"	: '<strong><var>person( 1 )</var> heeft nog <var>SOLUTION</var> liter benzine in <var>his( 1 )</var> tank.</strong>',
		"hint22"	: 'We kunnen <code><var>ATTENDEES</var></code> vermenigvuldigen met <code>\\dfrac{<var>N</var>}{<var>D</var>}</code> om te achterhalen hoeveel volwassenen er op de picknick waren.',
		"hint23"	: '<strong><var>SOLUTION</var> mensen op de picknick waren volwassenen.</strong>'
		}
})