({

	"titles" : {
		"nl" : {
			"Absolute value" : "Absolute waarde",
			"Absolute value equations" : "Absolute waarde vergelijking",
			"Rounding whole numbers" : "Afronden hele getallen",
			"Subtraction 1" : "Aftrekken 1",
			"Subtraction 2" : "Aftrekken 2",
			"Subtraction 3" : "Aftrekken 3",
			"Subtraction 4" : "Aftrekken 4",
			"Subtracting fractions" : "Aftrekken breuken",
			"Subtracting decimals" : "Aftrekken decimalen",
			"Subtracting fractions with common denominators" : "Aftrekken gelijkwaardige breuken",
			"Recognizing fractions" : "Breuken herkennen",
			"Recognizing fractions 0.5" : "Breuken herkennen 0.5",
			"Converting fractions to decimals" : "Breuken omzetten naar decimalen",
			"Fractions on the number line" : "Breuken op de getallenlijn",
			"Ordering fractions" : "Breuken op volgorde zetten",
			"Adding fractions" : "Breuken optellen",
			"Comparing fractions 1" : "Breuken vergelijken 1",
			"Comparing fractions 2" : "Breuken vergelijken 2",
			"Multiplying fractions 1" : "Breuken vermenigvuldigen 1",
			"Complementary and supplementary angles" : "Complementaire en supplementaire hoeken",
			"Complementary angles" : "Complementaire hoeken",
			"Converting decimals to fractions 1" : "Decimalen omzetten in breuken 1",
			"Converting decimals to fractions 2" : "Decimalen omzetten in breuken 2",
			"Converting decimals to percents" : "Decimalen omzetten naar percentages",
			"Decimals on the number line" : "Decimalen op de getallenlijn",
			"Division 0.5" : "Delen 0.5",
			"Division 1" : "Delen 1",
			"Division 1.5" : "Delen 1.5",
			"Division 2" : "Delen 2",
			"Division 3" : "Delen 3",
			"Division 4" : "Delen 4",
			"Units" : "Eenheden",
			"Properties of numbers 1" : "Getaleigenschappen 1",
			"Rounding numbers" : "Getallen afronden",
			"Ordering numbers" : "Getallen op volgorde zetten",
			"Number line" : "Getallenlijn",
			"Number line 2" : "Getallenlijn 2",
			"Number line 3" : "Getallenlijn 3",
			"Greatest common divisor" : "Grootste gemene deler",
			"Significant figures 1" : "Grote getallen 1",
			"Angles 1" : "Hoeken 1",
			"Angles 2" : "Hoeken 2",
			"Triangle angles 1" : "Hoeken van driehoeken",
			"Least common multiple" : "Kleinste gemene deler",
			"Telling time" : "Klokkijken",
			"Telling time 0.5" : "Klokkijken 0.5",
			"Reading line charts 1" : "Lijngrafiek lezen 1",
			"Ordering negative numbers" : "Negatieve getallen op volgorde zetten",
			"Adding negative numbers" : "Negatieve getallen optellen",
			"Prime factorization" : "Ontbinden in priemfactoren",
			"Addition 1" : "Optellen 1",
			"Addition 2" : "Optellen 2",
			"Addition 3" : "Optellen 3",
			"Addition 4" : "Optellen 4",
			"Adding decimals" : "Optellen decimalen",
			"Adding and subtracting fractions" : "Optellen en aftrekken van breuken",
			"Adding and subtracting negative numbers" : "Optellen en aftrekken van negatieve getallen",
			"Adding fractions with common denominators" : "Optellen gelijkwaardige breuken",
			"Converting percents to decimals" : "Percentage omzetten naar decimalen",
			"Recognizing percents" : "Percentages herkennen",
			"Prime numbers" : "Priemgetallen",
			"Graphs of sine and cosine" : "Sinus en Cosinus grafieken",
			"Triangle types" : "Soorten driehoeken",
			"Angle types" : "Soorten hoeken",
			"Reading bar charts 1" : "Staafgrafiek lezen 1",
			"Supplementary angles" : "Supplementaire hoeken",
			"Reading tables 1" : "Tabellen lezen 1",
			"Reading tables 2" : "Tabellen lezen 2",
			"Counting 1" : "Tellen 1",
			"Counting 2" : "Tellen 2",
			"Simplifying fractions" : "Vereenvoudig breuken",
			"Comparing absolute values" : "Vergelijken absolute waarden",
			"Multiplication 0.5" : "Vermenigvuldig 0.5",
			"Multiplication 1" : "Vermenigvuldig 1",
			"Multiplication 1.5" : "Vermenigvuldig 1.5",
			"Multiplication 2" : "Vermenigvuldig 2",
			"Multiplication 3" : "Vermenigvuldig 3",
			"Multiplication 4" : "Vermenigvuldig 4",
			"Multiplying and dividing negative numbers" : "Vermenigvuldigen en delen van negatieve getallen",
			"Multiplying decimals" : "Vermenigvuldigen van decimalen"
		}
	},

	"globals" : {
		"nl" : {
			"Veel" : "voorkomende woorden"
		}
	}

})