({
	"nl" : {
		"question1"	: 'If <var>person( 1 )</var> spends <var>X</var> weeks at camp, how many skateboarding tricks will <var>he( 1 )</var> know at the end of camp?',
		"question2"	: 'After <var>X</var> years, how many marathons will <var>person( 1 )</var> have run?',
		"question3"	: 'If <var>person( 1 )</var> buys <var>X</var> books for $<var>P</var> each, how much will the total bill be (assuming no sales tax)?',
		"question4"	: 'At the end of <var>X</var> months, how many articles will <var>he( 1 )</var> have had published in <i>The New York Times</i>?',
		"question5"	: 'If <var>person( 1 )</var> completes <var>P</var> exercises per week for the next <var>X</var> weeks, how many exercises will <var>he( 1 )</var> have completed in total?',
		"question6"	: 'If <var>person( 1 )</var> wants to earn more than $<var>R</var> this week, what is the minimum number of subscriptions <var>he( 1 )</var> needs to sell?',
		"question7"	: 'What is the minimum number of levels that <var>person( 1 )</var> needs to complete in the next hour to meet <var>his( 1 )</var> goal?',
		"question8" : 'If there are <var>X</var> left before winter, what is the minimum units of energy the bear needs to store up per month?',
		"question9" : 'If <var>person( 1 )</var> can typically master <var>P</var> songs per month, what is the minimum amount of months it will take <var>him( 1 )</var> to move to the maestro level?',
		
		"problem1"	: '{Before skateboarding camp <var>person( 1 )</var> knew how to do|<var>person( 1 )</var> already knows how to do} <var>Q</var> skateboarding tricks. {<var>person( 1 )</var> hopes to one day be able to do <var>randRange( 25, 50 )</var> tricks. |}{Every week, <var>person( 1 )</var> will be taught <var>P</var> tricks.|At skateboarding camp, <var>person( 1 )</var> will learn <var>P</var> tricks per week.}',
		"problem2"	: '<var>person( 1 )</var> has run <var>plural( Q, "marathon" )</var>{ and {plans|has commited to} to run <var>P</var> marathons per year.|. <var>He( 1 )</var> {plans|is commited} to run <var>P</var> marathons per year.}{ <var>person( 1 )</var> has been training for <var>randRange(2, 3)</var> months for this upcoming commitment.|}',
		"problem3"	: '{<var>person( 1 )</var> has a coupon for shipping from Amazon.com|<var>person( 1 )</var> has decided to purchase some books from Amazon.com}. {No matter how much <var>he( 1 )</var> purchases, shipping will cost $<var>Q</var>.|Shipping is set at a flat-rate of $<var>Q</var>, regardless of the number of books purchased.}',
		"problem4"	: '{<var>Q</var> articles have been published by <var>person( 1 )</var> in <i>The New York Times</i>|<var>person( 1 )</var> has written <var>Q</var> articles for <i>The New York Times</i>}{ (<var>Q - randRange(2, 8)</var> of them in the last year)|}{. <var>He( 1 )</var> has a new contract| and <var>he( 1 )</var> has a new contract} to write <var>plural( P, "article" )</var> per month for the next <var>X</var> months.',
		"problem5"	: '{After practicing for <var>randRange( 2, 5 )</var> months, |}<var>person( 1 )</var> {has reached proficiency|is proficient} in <var>Q</var> exercises on Khan Academy.',
		"problem6"	: '<var>person( 1 )</var> sells magazine subscriptions and earns $<var>P</var> for every new subscriber <var>he( 1 )</var> signs up. <var>person( 1 )</var> also earns a $<var>Q</var> weekly bonus regardless of how many magazine subscriptions <var>he( 1 )</var> sells.',
		"problem7"	: 'For every level <var>person( 1 )</var> completes in <var>his( 1 )</var> favorite game, <var>he( 1 )</var> earns <var>P</var> points. At the end of each hour spent playing the game, <var>person( 1 )</var> earns a bonus of <var>Q</var>. Name already has <var>10 * randRange( 500 / 10, 5000 / 10 )</var> in the game and wants to earn more than <var>R</var> additional points in the next hour.',
		"problem8"	: 'A bear named <var>person( 1 )</var> is preparing to hibernate for the winter. <var>he( 1 )</var> has already stored up <var>Q</var> units of energy and needs to store up at least <var>R</var> total units of energy before winter.',
		"problem9"	: 'To move up to the maestro level in <var>his( 1 )</var> piano school, <var>person( 1 )</var> needs to master at least <var>R</var> songs. <var>person( 1 )</var> has already mastered <var>Q</var> songs.',
		
		"hint1"		: 'Skateboarding tricks <var>he( 1 )</var> learns per week x Number of weeks at the camp + Skateboarding tricks <var>he( 1 )</var> already knows = Number of tricks known at the end of camp',
		"hint2"		: 'Skateboarding tricks <var>he( 1 )</var> learns per week = <code><var>P</var></code>',
		"hint3"		: 'Number of weeks at the camp = <code><var>X</var></code>',
		"hint4"		: 'Skateboarding tricks <var>he( 1 )</var> already knows = <code><var>Q</var></code>',
		"hint5"		: 'Number of tricks known at the end of camp = <code>r</code>',
		"hint6"		: '<strong><var>person( 1 )</var> will know <var>R</var> tricks at the end of camp.</strong>',
		"hint7"		: 'Number of marathons planned per year x Number of years + Number of marathons <var>he( 1 )</var> already ran = Total number of marathons',
		"hint8"		: 'Number of marathons planned per year = <code><var>P</var></code>',
		"hint9"		: 'Number of years = <code><var>X</var></code>',
		"hint10"	: 'Number of marathons <var>he( 1 )</var> already ran = <code><var>Q</var></code>',
		"hint11"	: 'Total number of marathons = <code>r</code>',
		"hint12"	: '<strong><var>person( 1 )</var> will have run <var>R</var> marathons at the end of <var>X</var> years.</strong>',
		"hint13"	: 'Cost of each book x Number of books bought + Cost of shipping = Bill total',
		"hint14"	: 'Cost of each book = <code><var>P</var></code>',
		"hint15"	: 'Number of books bought = <code><var>X</var></code>',
		"hint16"	: 'Cost of shipping = <code><var>Q</var></code>',
		"hint17"	: 'Bill total = <code>r</code>',
		"hint18"	: '<strong><var>person( 1 )</var> will spend $<var>R</var> on <var>his(1)</var> Amazon purchase.</strong>',
		"hint19"	: 'Number of articles to be written per month x Number of months writing articles + Number of articles already written = Total number of articles',
		"hint20"	: 'Number of articles to be written per month = <code><var>P</var></code>',
		"hint21"	: 'Number of months writing articles = <code><var>X</var></code>',
		"hint22"	: 'Number of articles already written = <code><var>Q</var></code>',
		"hint23"	: 'Total number of articles = <code>r</code>',
		"hint24"	: '<strong><var>person( 1 )</var> will have written <var>R</var> articles at the end of <var>X</var> months.</strong>',
		"hint25"	: 'Number of exercises to complete per week x Number of weeks completing exercises + Number of exercises already proficient in = Total number of exercises completed',
		"hint26"	: 'Number of exercises to complete per week = <code><var>P</var></code>',
		"hint27"	: 'Number of weeks completing exercises = <code><var>X</var></code>',
		"hint28"	: 'Number of exercises already proficient in = <code><var>Q</var></code>',
		"hint29"	: 'Total number of exercises completed = <code>r</code>',
		"hint30"	: '<strong><var>person( 1 )</var> will have completed <var>R</var> exercises at the end of <var>X</var> weeks.</strong>',
		"hint31"	: 'Dollars per subscription x Number of subscriptions sold + Weekly bonus > Minimum dollar amount to earn this week',
		"hint32"	: 'Dollars per subscription = <code><var>P</var></code>',
		"hint33"	: 'Weekly bonus = <code><var>Q</var></code>',
		"hint34"	: 'Minimum dollar amount to earn this week = <code><var>R</var></code>',
		"hint35"	: 'Number of subscriptions sold = <code>x</code>',
		"hint36"	: '<strong><var>person( 1 )</var> must sell at least <var>X</var> subscriptions this week.</strong>',
		"hint37"	: 'Points per level x Number of levels completed + Bonus points > Points goal',
		"hint38"	: 'Points per level = <code><var>P</var></code>',
		"hint39"	: 'Bonus points = <code><var>X</var></code>',
		"hint40"	: 'Points goal = <code><var>R</var></code>',
		"hint41"	: 'Number of levels completed = <code>x</code>',
		"hint42"	: '<strong><var>person( 1 )</var> needs to complete at least <var>X</var> levels in the next hour.</strong>',
		"hint43"	: 'Months left before winter x Units of energy stored per month + Units of energy already stored > Units of energy needed',
		"hint44"	: 'Months left before winter = <code><var>X</var></code>',
		"hint45"	: 'Units of energy already stored = <code><var>Q</var></code>',
		"hint46"	: 'Units of energy needed = <code><var>R</var></code>',
		"hint47"	: 'Units of energy stored per month = <code>p</code>',
		"hint48"	: '<strong><var>person( 1 )</var> needs to store up at least <var>P</var> units of energy before the winter.</strong>',
		"hint49"	: 'Songs to master per month x Number of months practicing + Songs already mastered > Songs needed for maestro level',
		"hint50"	: 'Songs to master per month = <code><var>P</var></code>',
		"hint51"	: 'Songs already mastered = <code><var>X</var></code>',
		"hint52"	: 'Songs needed for maestro level = <code><var>R</var></code>',
		"hint53"	: 'Number of months practicing = <code>x</code>',
		"hint54"	: '<strong>It will take <var>person( 1 )</var> at least <var>X</var> months to move to the maestro level.</strong>',
		}
})