({
	"nl" : {
		"exercise1"	: '{\'s Middags wees de thermometer een temperatuur aan van|Op een koude middag in februari was het buiten} <var>abs( X )</var> graden onder nul. {\'s Avonds was de temperatuur <var>Y</var> graden lager|Als je \'s avonds weer op de thermometer kijkt, zie je dat de temperatuur gedaald is met <var>Y</var> graden}.',
		"exercise2"	: 'Hoe koud was het \'s avonds?',
		"exercise3"	: '<span class="sol" data-forms="integer"><var>Z</var></span> graden',
		"exercise4"	: '{Toen <var>person( 1 )</var> \'s ochtends naar buiten ging om te gaan schaatsen|Toen <var>person( 1 )</var> zich voorbereidde op een dag lang schaatsen}, {keek <var>he( 1 )</var> op de thermometer en zag|hoorde <var>he( 1 )</var> op de radio} dat de temperatuur <var>abs( X )</var> graden onder nul was. Nadat <var>he( 1 )</var> {<var>( randRange( 1, 8 ))</var> uur geschaatst had| een lange dag geschaatst had} zag <var>he( 1 )</var> dat de temperatuur <var>Z</var> graden was.',
		"exercise5"	: 'Met hoeveel graden was de temperatuur gestegen?',
		"exercise6"	: '<span class="sol" data-forms="integer"><var>Y</var></span> graden',
		"exercise7"	: '<var>person( 1 )</var> dook <var>X</var> meter onder de oppervlakte toen <var>he( 1 )</var> een prachtige vis onder zich zag. {Van een afstand leek de vis ongeveer <var>randRange( 25, 35 )</var> cm groot. |}{Om een goede foto te kunnen nemen|Om de vis van dichtbij te bekijken}, dook <var>person( 1 )</var> <var>Y</var> meter totdat <var>he( 1 )</var> op dezelfde diepte was als de vis.',
		"exercise8"	: 'Waar was de vis ten opzichte van het wateroppervlak?',
		"exercise9"	: '<span class="sol" data-forms="integer"><var>Z</var></span> meter',
		"exercise10"	: 'Een dolfijn sprong vanaf <var>X</var> meter onder het wateroppervlak en dook door een hoepel op <var>Y</var> meter boven het water. {De sprong duurde ongeveer 1,<var>randRange( 1, 9 )</var> seconde.|Het water spatte na de sprong ongeveer 3,<var>randRange( 1, 9 )</var> meter op.}',
		"exercise11"	: 'Hoeveel meter legde de dolfijn af om het hoogste punt van zijn sprong te bereiken?',
		"exercise12"	: '<span class="sol" data-forms="integer"><var>Z</var></span> meter',		
		"exercise13"	: '<var>person( 1 )</var> leent van de bank &euro;<var>( X )</var> om een voetbalkamp te organiseren. <var>person( 1 )</var> gebruikt de lening om materiaal aan te schaffen en trainers te betalen. Gedurende de zomer nemen <var>N</var> kinderen deel aan het kamp. Zij betalen elk &euro;<var>COST</var> om deel te nemen. <var>person( 1 )</var> gebruikt al het geld dat hij van de deelnemers ontvangt om de lening af te lossen.',
		"exercise14"	: 'Wat is aan het einde van de zomer het saldo van <var>person( 1 )</var>?',
		"hint1"		: '<code><var>abs( X )</var></code> graden onder nul is hetzelfde als <code><var>X</var>^{\\circ}</code>.',
		"hint2"		: 'Omdat de de temperatuur met <code><var>Y</var>^{\\circ}</code> daalde, trek je dit aantal af van de middagtemperatuur.',
		"hint3"		: 'De temperatuur in de avond was <code><var>Z</var>^{\\circ}</code>.',
		"hint4"		: '<code><var>abs( X )</var></code> graden onder nul is hetzelfde als <code><var>X</var>^{\\circ}</code>.',
		"hint5"		: 'Verandering in temperatuur = uiteindelijke temperatuur - oorspronkelijke temperatuur',
		"hint6"		: 'Verandering in temperatuur = <code><var>Z</var>^{\\circ} - (<var>X</var>^{\\circ}) = <var>Z</var>^{\\circ} - <var>X</var>^{\\circ} = <var>Y</var>^{\\circ}</code>',
		"hint7"		: 'De temperatuur was gestegen met <code><var>Y</var>^{\\circ}</code>.',
		"hint8"		: '<var>person( 1 )</var> was oorspronkelijk <code><var>X</var></code> meter onder de oppervlakte, wat geschreven kan worden als een negatief getal, <code>-<var>X</var></code> meter.',
		"hint9"		: '<var>person( 1 )</var> dook <code><var>Y</var></code> meter naar beneden, dus die afstand kunnen we aftrekken van het oorspronkelijke niveau van <var>person( 1 )</var> om te achterhalen hoe diep de vis was.',
		"hint10"		: 'De positie van de vis ten opzichte van het wateroppervlak <code>=-<var>X</var>\\text{ meter} - <var>Y</var>\\text{ meter} = <var>Z</var>\\text{ meter}</code>',
		"hint11"		: 'De dolfijn was oorspronkelijk <var>X</var> meter onder de oppervlakte, wat geschreven kan worden als een negatief getal, -<var>X</var> meter.',
		"hint12"		: 'Hoogte die dolfijn sprong = hoogste punt - oorspronkelijke positie',
		"hint13"		: '<code><var>Y</var>\\text{ meter} - (-<var>X</var>\\text{ meter}) = <var>Y</var>\\text{ meter} + <var>X</var>\\text{ meter} = <var>Z</var>\\text{ meter}</code>',
		"hint14"		: '<var>person( 1 )</var> begon de zomer met een schuld van <code>&euro;<var>( X )</var></code>, wat geschreven kan worden als een negatief getal, <code>-&euro;<var>( X )</var></code>.',
		"hint15"		: 'Hoeveelheid geld dat <var>person( 1 )</var> kreeg van deelnemers = <code><var>N</var> \\times &euro;<var>COST</var>=&euro;<var>(  Y )</var></code>',
		"hint16"		: 'schuld + verdiensten = saldo van <var>person( 1 )</var>',
		"hint17"		: '<code>-&euro;<var>( X )</var> + &euro;<var>( Y )</var> = -&euro;<var>( Z )</var></code>'
		}
})