({
	"nl" : {
		"list1"		: 'Kite',
		"list2"		: 'Trapezoid',
		"list3"		: 'Isosceles Trapezoid',
		"list4"		: 'Parallelogram',
		"list5"		: 'Rhombus',
		"list6"		: 'Rectangle',
		"list7"		: 'Square',
		"list8"		: 'None of the above',
		
		"problem1"	: 'What is the type of this quadrilateral? Be as specific as possible with the given data.',
	
		"hint1"		: 'This figure has two parallel sides.',
		"hint2"		: 'It also has 2 pairs of adjacent angles which are supplementary.',
		"hint3"		: 'It is a trapezoid.',
		"hint4"		: 'This figure has two parallel sides.',
		"hint5"		: 'It also has 2 pairs of adjacent angles which are supplementary.',
		"hint6"		: 'It is a trapezoid.',
		"hint7"		: 'However, its legs are equal, so it is an isosceles trapezoid.',
		"hint8"		: 'Opposite angles of this  quadrilateral are equal.',
		"hint9"		: 'Adjacent angles are supplementary.',
		"hint10"	: 'It has 2 pairs of parallel sides.',
		"hint11"	: 'Parallel sides are equal.',
		"hint12"	: 'Therefore it is a parallelogram.',
		"hint13"	: 'This quadrilateral has 2 pairs of parallel sides.',
		"hint14"	: 'Its angles are equal to 90.',
		"hint15"	: 'Therefore it is a rectangle.',
		"hint16"	: 'This quadrilateral has 2 pairs of parallel sides.',
		"hint17"	: 'Its angles are equal to 90.',
		"hint18"	: 'All sides are equal.',
		"hint19"	: 'Therefore it is a square.',
		"hint20"	: 'This quadrilateral has two pairs of equal sides.',
		"hint21"	: 'Those sides are adjacent.',
		"hint22"	: 'It also has a pair of equal angles, positioned between the non-equal sides.',
		"hint23"	: 'It is a kite.',
		"hint24"	: 'This quadrilateral has all sides equal.',
		"hint25"	: 'Therefore it is a rhombus.'
		}
})