({
	"nl" : {
		"question1"	: 'First consider the expression for:',
		"question2"	: 'The sum of <code><var>A</var></code> and the product of <code><var>B</var></code> and <code>x</code>.',
		"question3"	: 'Now select the answer that matches the following:',
		"question4"	: '<b><code><var>D</var></code> plus the quantity of <code><var>C</var></code> times that expression</b>',
		"question5"	: 'the sum of <code><var>A</var></code> and the quantity of <code><var>B</var></code> times <code>x</code>',
		"question6"	: '<b><code><var>D</var></code> plus the product of <code><var>C</var></code> and that expression</b>',
		"question7"	: '<code><var>A</var></code> plus the product of <code><var>B</var></code> and <code>x</code>',
		"question8"	: '<b>Take the quantity of <code><var>C</var></code> times that expression and then add <code><var>D</var></code>.</b>',
		"question9"	: '<code><var>A</var></code> plus the quantity of <code><var>B</var></code> times <code>x</code>',
		"question10"	: '<b>Take the product of <code><var>C</var></code> and that expression and then add <code><var>D</var></code>.</b>',
		"question11"	: 'Take the product of <code><var>B</var></code> and <code>x</code> and add <code><var>A</var></code>.',
		"question12"	: '<b>The sum of <code><var>D</var></code> and the product of <code><var>C</var></code> and that expression.</b>',
		"question13"	: 'Take the quantity of <code><var>B</var></code> times <code>x</code> and add <code><var>A</var></code>.',
		"question14"	: '<b>the sum of <code><var>D</var></code> and the product of <code><var>C</var></code> and that expression</b>',
		"hint1"		: 'What is <span class="hint_orange">the product of <code><var>B</var></code> and <code>x</code></span>?',
		"hint2"		: 'What is <span class="hint_blue">the sum of <code><var>A</var></code></span> and <code class="hint_orange"><var>expr(["*", B, "x"])</var></code>?',
		"hint3"		: 'What is <span class="hint_orange">the quantity of <code><var>C</var></code> times that expression</span>?',
		"hint4"		: 'What is <span class="hint_blue"><code><var>D</var></code> plus</span> <code>\color{orange}{<var>expr(["*", C,["+",["*", B, "x"], A]])</var>}</code>?',
		"hint5"		: 'What is <span class="hint_orange">the quantity of <code><var>B</var></code> times <code>x</code></span>?',
		"hint6"		: 'What is <span class="hint_blue">the sum of <code><var>A</var></code></span> and <code class="hint_orange"><var>expr(["*", B, "x"])</var></code>?',
		"hint7"		: 'What is <span class="hint_orange">the product of <code><var>C</var></code> times that expression</span>?',
		"hint8"		: 'What is <span class="hint_blue"><code><var>D</var></code> plus</span> <code>\color{orange}{<var>expr(["*", C,["+",["*", B, "x"], A]])</var>}</code>?',
		"hint9"		: 'What is <span class="hint_orange">the product of <code><var>B</var></code> and <code>x</code></span>?',
		"hint10"	: 'What is <span class="hint_blue"><code><var>A</var></code> plus</span> <code class="hint_orange"><var>expr(["*", B, "x"])</var></code>?',
		"hint11"		: 'What is <span class="hint_orange">the quantity of <code><var>C</var></code> times that expression</span>?',
		"hint12"		: 'What does <span class="hint_blue">adding <code><var>D</var></code></span> to <code>\color{orange}{<var>expr(["*", C,["+",["*", B, "x"], A]])</var>}</code> do?',
		"hint13"		: 'What is <span class="hint_orange">the quantity of <code><var>B</var></code> times <code>x</code></span>?',
		"hint14"		: 'What is <span class="hint_blue"><code><var>A</var></code> plus</span> <code class="hint_orange"><var>expr(["*", B, "x"])</var></code>?',
		"hint15"		: 'What is <span class="hint_orange">the product of <code><var>C</var></code> times that expression</span>?',
		"hint16"		: 'What does <span class="hint_blue">adding <code><var>D</var></code></span> to <code>\color{orange}{<var>expr(["*", C,["+",["*", B, "x"], A]])</var>}</code> do?',
		"hint17"		: 'What is <span class="hint_orange">the product of <code><var>B</var></code> and <code>x</code></span>?',
		"hint18"		: 'What does <span class="hint_blue">adding <code><var>A</var></code></span> to <code class="hint_orange"><var>expr(["*", B, "x"])</var></code> do?',
		"hint19"		: 'What is <span class="hint_orange">the quantity of <code><var>C</var></code> times that expression</span>?',
		"hint20"	: 'What is <span class="hint_blue">the sum of <code><var>D</var></code> and </span><code>\color{orange}{<var>expr(["*", C,["+",["*", B, "x"], A]])</var>}</code>?',
		"hint21"	: 'What is <span class="hint_orange">the quantity of <code><var>B</var></code> times <code>x</code></span>?',
		"hint22"	: 'What does <span class="hint_blue">adding <code><var>A</var></code></span> to <code class="hint_orange"><var>expr(["*", B, "x"])</var></code> do?',
		"hint23"	: 'What is <span class="hint_orange">the product of <code><var>C</var></code> times that expression</span>?',
		"hint24"	: 'What is <span class="hint_blue">the sum of <code><var>D</var></code> and </span><code>\color{orange}{<var>expr(["*", C,["+",["*", B, "x"], A]])</var>}</code>?',
		"hint25"	: "Let's break this problem into smaller and easier pieces.",
		"hint26"	: 'So the entire expression we are considering can be written as <code><var>expr(["+",["*", C,["+",["*", B, "x"], A]], D])</var></code>.'
		}
})