Query.extend( KhanUtil, {
Exercises: [
    {
        "covers": [], 
        "display_name": "Addition 1", 
        "h_position": 0, 
        "is_ancestor_review_candidate": null, 
        "is_review_candidate": false, 
        "kind": "Exercise", 
        "last_done": "2011-05-15T18:37:42", 
        "live": true, 
        "longest_streak": 12, 
        "name": "addition_1", 
        "next_review": "2011-08-20T18:10:01", 
        "phantom": false, 
        "points": 13, 
        "prerequisites": [], 
        "proficient": true, 
        "required_streak": 10, 
        "review": false, 
        "seconds_per_fast_problem": 4.0, 
        "short_display_name": "Add. 1", 
        "status": "Proficient", 
        "streak": 12, 
        "suggested": false, 
        "summative": false, 
        "total_done": 12, 
        "user_exercise": {
            "exercise": "addition_1", 
            "exercise_model": {
                "covers": [], 
                "display_name": "Addition 1", 
                "h_position": 0, 
                "kind": "Exercise", 
                "live": true, 
                "name": "addition_1", 
                "prerequisites": [], 
                "required_streak": 10, 
                "seconds_per_fast_problem": 4.0, 
                "short_display_name": "Add. 1", 
                "summative": false, 
                "v_position": 3
            }, 
            "exercise_states": {
                "endangered": false, 
                "phantom": false, 
                "proficient": true, 
                "reviewing": false, 
                "struggling": false, 
                "suggested": false, 
                "summative": false
            }, 
            "first_done": "2011-05-15T18:36:32", 
            "kind": "UserExercise", 
            "last_done": "2011-05-15T18:37:42", 
            "last_review": "2011-05-15T18:37:41", 
            "longest_streak": 12, 
            "next_points": 13, 
            "proficient_date": "2011-05-15T18:37:31", 
            "required_streak": 10, 
            "seconds_per_fast_problem": 5.0, 
            "streak": 12, 
            "summative": false, 
            "total_correct": 12, 
            "total_done": 12, 
            "user": "amygervis"
        }, 
        "v_position": 3
    }, 
    {
        "covers": [], 
        "display_name": "Subtraction 1", 
        "h_position": 1, 
        "is_ancestor_review_candidate": null, 
        "is_review_candidate": false, 
        "kind": "Exercise", 
        "last_done": "2011-05-15T18:49:40", 
        "live": true, 
        "longest_streak": 10, 
        "name": "subtraction_1", 
        "next_review": "2011-08-20T18:09:13", 
        "phantom": false, 
        "points": 15, 
        "prerequisites": [
            "addition_1"
        ], 
        "proficient": true, 
        "required_streak": 10, 
        "review": false, 
        "seconds_per_fast_problem": 4.0, 
        "short_display_name": "Sub. 1", 
        "status": "Suggested", 
        "streak": 10, 
        "suggested": false, 
        "summative": false, 
        "total_done": 10, 
        "user_exercise": {
            "exercise": "subtraction_1", 
            "exercise_model": {
                "covers": [], 
                "display_name": "Subtraction 1", 
                "h_position": 1, 
                "kind": "Exercise", 
                "live": true, 
                "name": "subtraction_1", 
                "prerequisites": [
                    "addition_1"
                ], 
                "required_streak": 10, 
                "seconds_per_fast_problem": 4.0, 
                "short_display_name": "Sub. 1", 
                "summative": false, 
                "v_position": 5
            }, 
            "exercise_states": {
                "endangered": false, 
                "phantom": false, 
                "proficient": true, 
                "reviewing": false, 
                "struggling": false, 
                "suggested": false, 
                "summative": false
            }, 
            "first_done": "2011-05-15T18:48:53", 
            "kind": "UserExercise", 
            "last_done": "2011-05-15T18:49:40", 
            "last_review": "2011-05-15T18:49:39", 
            "longest_streak": 10, 
            "next_points": 15, 
            "proficient_date": "2011-05-15T18:49:40", 
            "required_streak": 10, 
            "seconds_per_fast_problem": 4.0, 
            "streak": 10, 
            "summative": false, 
            "total_correct": 10, 
            "total_done": 10, 
            "user": "amygervis"
        }, 
        "v_position": 5
    }]}); 